name: 'Hello test'
description: 'Hello test'
inputs:
  token:
    description: "PT"
    required: true  
runs:
  using: "composite"
  steps:
    - run: echo "Here I am"
      shell: bash
      env:
       GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
  
