name: 'Deploy Package'
description: 'Deploying maven package to github package registry'
inputs:
  version:
    description: 'Package Version'
    required: true
    default: 1.0.0
  file:
    description: 'File for deploy'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
       mvn \
       deploy:deploy-file \
       -DgroupId=alex \
       -DartifactId=test \
       -Dversion=${{ inputs.version }} \
       -Dpackaging=zip \
       -Dfile="${{ inputs.file }}.zip" \
       -DrepositoryId="github" \
       -Durl="https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
      shell: bash
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  