name: 'ESlint'
description: 'EsLint check'
inputs:
  GITHUB_TOKEN:
    description: 'PA Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        npm install -g eslint 
        run: npx eslint --init
        run: npx eslint -c ${{ github.action_path }}/.eslintrc src/
      shell: bash
      env:
       GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
  
